"""
DocQuery Gaps — Report Generator

Produces Markdown and CSV content-gap reports from clustered questions.
Integrates with gaps.tracker (data) and gaps.clusterer (grouping).
"""

import csv
import io
from datetime import datetime

from gaps.tracker import get_gaps
from gaps.clusterer import cluster_gaps, GapCluster


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _priority(cluster: GapCluster) -> str:
    if cluster.total_count >= 3:
        return "high"
    if cluster.total_count == 2:
        return "medium"
    return "low"


def _suggested_action(cluster: GapCluster) -> str:
    """Infer a documentation action from the question text."""
    q = cluster.representative.lower()
    if any(w in q for w in ["how", "set up", "install", "configure", "enable"]):
        return "Add how-to / tutorial"
    if any(w in q for w in ["what is", "what are", "explain", "difference", "vs "]):
        return "Add conceptual explanation"
    if any(w in q for w in ["error", "fail", "broken", "issue", "problem", "not work"]):
        return "Add troubleshooting section"
    if any(w in q for w in ["api", "endpoint", "request", "response", "param", "header"]):
        return "Expand API reference"
    if any(w in q for w in ["limit", "rate", "quota", "throttl"]):
        return "Document rate limits / quotas"
    if any(w in q for w in ["auth", "token", "oauth", "key", "secret", "credential"]):
        return "Expand authentication docs"
    return "Create new documentation section"


# ---------------------------------------------------------------------------
# Markdown report
# ---------------------------------------------------------------------------

def generate_markdown_report(collection: str) -> str:
    """
    Generate a Markdown content-gap report with clustered questions.

    Sections:
    - High priority  (asked 3+ times)
    - Medium priority (asked exactly 2 times)
    - Low priority   (asked once)

    Variant questions (same cluster, different wording) are shown as
    indented sub-rows for transparency.
    """
    gaps = get_gaps(collection)
    if not gaps:
        return (
            f"# Documentation Content Gaps — {collection}\n\n"
            "No open content gaps detected. Your documentation looks comprehensive!"
        )

    clusters = cluster_gaps(gaps)
    high = [c for c in clusters if c.total_count >= 3]
    medium = [c for c in clusters if c.total_count == 2]
    low = [c for c in clusters if c.total_count == 1]

    total_asked = sum(c.total_count for c in clusters)

    lines = [
        f"# Documentation Content Gaps — {collection}",
        f"Generated: {datetime.utcnow().strftime('%Y-%m-%d')}",
        "",
        f"**{len(clusters)} gap clusters** across **{total_asked} questions asked**",
        "",
    ]

    sections = [
        ("## High Priority (asked 3+ times)", high),
        ("## Medium Priority (asked 2 times)", medium),
        ("## Low Priority (asked once)", low),
    ]

    for heading, group in sections:
        if not group:
            continue
        lines.append(heading)
        lines.append("")
        lines.append(
            "| Topic | Times Asked | Nearest Section | Confidence | Suggested Action |"
        )
        lines.append(
            "|-------|-------------|-----------------|------------|------------------|"
        )
        for c in group:
            lines.append(
                f"| {c.representative} "
                f"| {c.total_count} "
                f"| {c.nearest_section or '—'} "
                f"| {c.min_confidence:.2f} "
                f"| {_suggested_action(c)} |"
            )
            # Show variant questions as indented rows
            for variant in c.questions[1:]:
                lines.append(f"| &nbsp;&nbsp;↳ *{variant}* | | | | |")
        lines.append("")

    lines.append("---")
    lines.append(
        f"*Generated by DocQuery · {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*"
    )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CSV report
# ---------------------------------------------------------------------------

def generate_csv_report(collection: str) -> str:
    """
    Generate a CSV content-gap report suitable for spreadsheet import.

    Columns:
        cluster_topic, variant_questions, times_asked, priority,
        confidence_score, nearest_section, first_asked, last_asked,
        suggested_action
    """
    gaps = get_gaps(collection)
    clusters = cluster_gaps(gaps) if gaps else []

    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow([
        "cluster_topic",
        "variant_questions",
        "times_asked",
        "priority",
        "confidence_score",
        "nearest_section",
        "first_asked",
        "last_asked",
        "suggested_action",
    ])

    for c in clusters:
        writer.writerow([
            c.representative,
            " | ".join(c.questions[1:]) if len(c.questions) > 1 else "",
            c.total_count,
            _priority(c),
            f"{c.min_confidence:.2f}",
            c.nearest_section or "",
            c.first_asked or "",
            c.last_asked or "",
            _suggested_action(c),
        ])

    return buf.getvalue()
