"""
DocQuery Gaps — Content Gap Tracker
Logs low-confidence queries as documentation content gaps.
"""

import json
import sqlite3
import os
from datetime import datetime
from contextlib import contextmanager

DB_PATH = os.getenv("DOCQUERY_GAPS_DB", "./docquery_gaps.db")


def init_gaps_db():
    """Initialize the content gaps database."""
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS content_gaps (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            question TEXT NOT NULL,
            collection TEXT NOT NULL,
            session_id TEXT,
            confidence_score REAL,
            top_retrieval_score REAL,
            nearest_section TEXT,
            status TEXT DEFAULT 'open',
            timestamp TEXT DEFAULT (datetime('now'))
        )
    """)
    conn.execute("CREATE INDEX IF NOT EXISTS idx_gaps_collection ON content_gaps(collection)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_gaps_status ON content_gaps(status)")
    conn.commit()
    conn.close()


@contextmanager
def get_db():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    try:
        yield conn
    finally:
        conn.close()


def log_gap(
    question: str,
    collection: str,
    session_id: str = "",
    confidence_score: float = 0.0,
    top_retrieval_score: float = 0.0,
    nearest_section: str = "",
):
    """Log a content gap from a low-confidence query."""
    with get_db() as conn:
        conn.execute(
            """INSERT INTO content_gaps
            (question, collection, session_id, confidence_score, top_retrieval_score, nearest_section)
            VALUES (?, ?, ?, ?, ?, ?)""",
            (question, collection, session_id, confidence_score, top_retrieval_score, nearest_section),
        )
        conn.commit()


def get_gaps(collection: str, status: str = "open", limit: int = 50) -> list[dict]:
    """Get content gaps for a collection."""
    with get_db() as conn:
        rows = conn.execute(
            """SELECT question, COUNT(*) as count,
                MIN(confidence_score) as min_confidence,
                MAX(top_retrieval_score) as max_retrieval,
                nearest_section, MIN(timestamp) as first_asked, MAX(timestamp) as last_asked
            FROM content_gaps
            WHERE collection = ? AND status = ?
            GROUP BY question
            ORDER BY count DESC, last_asked DESC
            LIMIT ?""",
            (collection, status, limit),
        ).fetchall()

    return [dict(r) for r in rows]


def update_gap_status(gap_id: int, status: str):
    """Update a gap's status (open, resolved, out_of_scope)."""
    with get_db() as conn:
        conn.execute("UPDATE content_gaps SET status = ? WHERE id = ?", (status, gap_id))
        conn.commit()


def get_gap_report(collection: str) -> str:
    """Generate a Markdown gap report."""
    gaps = get_gaps(collection)

    if not gaps:
        return f"# Documentation Content Gaps — {collection}\n\nNo content gaps detected."

    high_priority = [g for g in gaps if g["count"] >= 3]
    medium_priority = [g for g in gaps if g["count"] < 3]

    report = f"# Documentation Content Gaps — {collection}\n"
    report += f"Generated: {datetime.utcnow().strftime('%Y-%m-%d')}\n\n"

    if high_priority:
        report += "## High Priority (asked 3+ times)\n\n"
        report += "| Question | Times Asked | Nearest Section | Confidence |\n"
        report += "|----------|-------------|-----------------|------------|\n"
        for g in high_priority:
            report += f"| {g['question']} | {g['count']} | {g['nearest_section']} | {g['min_confidence']:.2f} |\n"

    if medium_priority:
        report += "\n## Medium Priority (asked 1-2 times)\n\n"
        report += "| Question | Times Asked | Nearest Section | Confidence |\n"
        report += "|----------|-------------|-----------------|------------|\n"
        for g in medium_priority:
            report += f"| {g['question']} | {g['count']} | {g['nearest_section']} | {g['min_confidence']:.2f} |\n"

    report += f"\n---\n*Generated by DocQuery on {datetime.utcnow().strftime('%Y-%m-%d %H:%M')}*\n"
    return report
